# Generated by Django 4.2.16 on 2024-10-16 19:11

import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                error_messages={"unique": "A user with that username already exists."},
                help_text="Required. 50 characters or fewer. Letters, digits and @/./+/-/_ only.",
                max_length=50,
                unique=True,
                validators=[
                    django.contrib.auth.validators.UnicodeUsernameValidator(),
                    django.core.validators.MinLengthValidator(
                        3, "Username must be at least 3 characters long."
                    ),
                ],
                verbose_name="Username",
            ),
        ),
    ]
